[package]
name = "game-gfx"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]

[features]
logging = ["log", "game-ecs/logging"]

[dependencies]
log = { version = "0.4.16", optional = true }
semver = "1.0.6"

game-ecs = { path = "../game-ecs" }
game-vk = { path = "../game-vk" }
