[package]
name = "game-gfx"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]

[dependencies]
ash = "0.37.0"
lazy_static = "1.4.0"
log = "0.4.16"
semver = "1.0.6"

game-ecs = { path = "../game-ecs" }
game-vk = { path = "../game-vk" }
