[package]
name = "game-bin"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game-cfg = { path = "../game-cfg" }
log = "0.4.14"
simplelog = "0.11.2"
