[package]
name = "game-lst"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]

[[bin]]
name = "game-list"
path = "src/main.rs"


[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
num-traits = "0.2.15"

game-gfx = { path = "../game-gfx" }
