[package]
name = "game-evt"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]

[dependencies]
async-trait = "0.1.53"
futures = "0.3.21"
log = "0.4.14"
tokio = { version = "1.18", features = ["time"] }
winit = "0.26"

game-utl = { path = "../game-utl" }
