[package]
name = "game-vk"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]

[dependencies]
ash = { version = "0.37.0", features = ["loaded"] }
log = "0.4.16"
semver = "1.0.6"

game-utl = { path = "../game-utl" }
